# Generated by Django 4.2.5 on 2023-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyapi',
            old_name='updated_on',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='companyapi',
            old_name='id',
            new_name='company_id',
        ),
        migrations.AlterField(
            model_name='companyapi',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companyapi',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Mobiles Phones', 'Mobile Phones')], max_length=100),
        ),
    ]
